### ISSUE TITLE
Add support for NPF poll blocks

### ISSUE THREAD

**Issue by the-blank-x** [syeopite/npf-renderer#6]
Opening https://pb.bloat.cat/garfieldildo/722604771204333568/have-you-ever-used-tumblr-live-before-yes-i gives a "Unsupported content placeholder: Hello! I'm a placeholder for the unsupported 'poll' type NPF content block. Please report me!":

![](https://github.com/syeopite/priviblur/assets/45762106/5c8d4ce6-9d68-41d2-a819-673505a54fb1)

**Comment by syeopite** [comment]
Polls will definitely be added sooner or later. Right now, its main blocking point is just that I'm not exactly sure how to implement it API design wise 😅

Polls require an additional request in order to be able to fetch poll results, except `npf-renderer` is supposed to be its own thing and probably shouldn't be doing any additional requests. So I'm not exactly sure how that should be rectified.

**Comment by the-blank-x** [comment]
One idea is to give the `TimelinePost` and `TimelinePostTrail` a `polls: dict[str, PollResults]` field (or perhaps a `poll: Optional[PollResults]` field, considering that there can only be one poll per post according to [three] [seperate] [blogs]), then you could do something like this for each post:
```python3
async def fill_polls(posts: list[Union[TimelinePost, TimelinePostTrail]]):
    for post in posts:
        for block in post.content:
            if block["type"] == "poll":
                poll_id = block["clientId"]
                poll = await request.app.ctx.TumblrAPI.poll_results(post.name, post.id, poll_id)
                post.polls[poll_id] = priviblur_extractor.parse_item(poll)
```

Afterwards, you can call `npf_renderer.format_npf` with the content, layout, and poll information. If you want, I can "verbalise" this with a patch/diff on Priviblur's side.

[three]: https://nobodysuspectsthebutterfly.tumblr.com/post/706893767017447424
[seperate]: https://5ummit.tumblr.com/post/706824840431239168/important-things-ive-learned-about-the-new-tumblr
[blogs]: https://priviblur.zangetsu.kaizoku.cyou/gotinterest/706984835382640640/polls-masterpost-updated-1202023

**Comment by syeopite** [comment]
In the end I decided to go with a similar but different approach of having a callback function passed into `format_npf` that'll request the poll information when called.
